[package]
name = "airplay"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures-util = "0.3.28"
mdns = "3.0.0"
tokio = { version = "1", features = ["full"] }
